### ISSUE TITLE
see this 3 problem 

### ISSUE THREAD

**Issue by helloanime** [himanshu8443/8-Stream#3]
@himanshu8443 

1}can you make some thing like when we go to animes then it will automatically shift to {consument} and anime's are only available in dub sub are not available plz check

![Screenshot (10)](https://github.com/user-attachments/assets/6c31caaf-15d0-47e0-a440-c854834cfb7a)
![Screenshot (9)](https://github.com/user-attachments/assets/ec657953-a5f1-4eea-9d7c-3fd12c757a86)

2}All anime's as well as series episodes a not showing and can you add next episode button in bottom near settings
![Screenshot (11)](https://github.com/user-attachments/assets/191bee88-4321-4d8a-a09b-2a6a7c487019)

3} fix play button is not showing problem 
![361322395-93ae6e90-6bda-47e0-aee6-25fc702e7b9b](https://github.com/user-attachments/assets/9d28c3f2-5cdd-4906-84da-8c1363ebe99b)

thats all and this side is very nice i like it .
@himanshu8443

**Comment by himanshu8443** [comment]
I am sorry but this project is not actively developed now, still I will try these problems when I get time.
Also, you want an Android app to watch movies and anime I am working on this https://github.com/Zenda-Cross/vega-app

**Comment by helloanime** [comment]
@himanshu8443 

can you plz solve the problem for play button not showing in mobile and all ep are not showing of anime's and web series only 1 season is showing. fix it . i send ss above check waiting...............

i will use vega-app too.

@himanshu8443

**Comment by himanshu8443** [comment]
please be patient

**Comment by anixplay9** [comment]
Sorry ! Ok ......

**Comment by helloanime** [comment]
sorry ! oky @himanshu8443

**Comment by himanshu8443** [comment]
I updated it are you still facing the issue
