### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by Saqijutt4200** [himanshu8443/8-Stream#9]
@himanshu8443 Brother, can you tell me where I will get the API key from? I have installed the 8-stream API here, and the 8-stream project on 'vidsrc-eta-mocha.vercel.app' and 'https://vidscr.netlify.app'. Where can I find the API for the 8-stream that will provide the stream? Please help.

**Comment by himanshu8443** [comment]
this is the API repo https://github.com/himanshu8443/8StreamApi

**Comment by Saqijutt4200** [comment]
I have successfully deployed my API at https://vidsrc-eta-mocha.vercel.app/, but I don’t understand how to connect this API with https://vidscr.netlify.app/ so that it displays the streaming URL.

I feel like this question might seem stupid to you, but I am new to Next.js projects and currently learning.

**Comment by himanshu8443** [comment]
Do you know how to use the .env file?

**Comment by Saqijutt4200** [comment]
No
![Screenshot_20241219-034228](https://github.com/user-attachments/assets/18bd3d45-d99d-4105-b187-f040c58ebbe9)
